### PR TITLE
Updated Readme file

### PR DESCRIPTION
**Pull request by ViswaAnoopNerella**
Added table of contents and some useful information.

Brought the Automated Publishing to top and manual packaging and publishing to bottom

### CODE REVIEW

**Review by ksanita — CHANGES_REQUESTED** [review]
The section on how to add the package repo to the visual studio package manager should be up at the top. 

General layout should probably be something like:

1. How to get the nuget packages. Basically the most basic steps for using our repos. Show what they need to do to open our libraries in visual studio without getting a bunch of errors.
2. How to update already created repos (updating version numbers and the readme, how to do pre-release, creating git releases, etc.). Basically the stuff the team will be doing most often as they add new devices and fix bugs in current ones.
3. How to create a new repo with automatic packaging. Just what people need to do when they create a new API library.
4. Additional info that may be useful (like creating a nuget package without automation)

**Review by kamasanis — APPROVED** [review]

**Comment by ViswaAnoopNerella** [comment]
> The section on how to add the package repo to the visual studio package manager should be up at the top.
> 
> General layout should probably be something like:
> 
> 1. How to get the nuget packages. Basically the most basic steps for using our repos. Show what they need to do to open our libraries in visual studio without getting a bunch of errors.
> 2. How to update already created repos (updating version numbers and the readme, how to do pre-release, creating git releases, etc.). Basically the stuff the team will be doing most often as they add new devices and fix bugs in current ones.
> 3. How to create a new repo with automatic packaging. Just what people need to do when they create a new API library.
> 4. Additional info that may be useful (like creating a nuget package without automation)

@ksanita  Made the changes accordingly. Please go over.

**Review by ksanita — COMMENTED** [review]
Move the notes on making the personal access token to the first section, since that is required for adding the github packages repo to Visual Studio. Once added and the repo is opened in the package manager, it will prompt the user for a username and password. Username is github login email, password is personal access token value.

**Comment by ViswaAnoopNerella** [comment]
> Move the notes on making the personal access token to the first section, since that is required for adding the github packages repo to Visual Studio. Once added and the repo is opened in the package manager, it will prompt the user for a username and password. Username is github login email, password is personal access token value.

@ksanita Changes completed.

**Review by ksanita — APPROVED** [review]
Pushed a small update reordering the login process for the package manager, but otherwise looks good now. I recommend pinging the team and letting them know the guide has been updated.

**Pull request merged**
